package com.gini.entity.v2;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDbBean
public class Employee {

    @Getter(onMethod = @__({
            @DynamoDbPartitionKey,
            @DynamoDbAttribute("employeeId")
    }))
    private String employeeId;


    @Getter(onMethod = @__({@DynamoDbAttribute("firstName")}))
    private String firstName;


    @Getter(onMethod = @__({
            @DynamoDbAttribute("lastName")}))
    private String lastName;

    @Getter(onMethod = @__({@DynamoDbAttribute("email")}))
    private String email;

    @Getter(onMethod = @__({@DynamoDbAttribute("department")}))
    private Department department;

//    @DynamoDbPartitionKey
//    @DynamoDbAttribute("employeeId")
//    public String getEmployeeId() {
//        return employeeId;
//    }

//    public void setEmployeeId(String employeeId) {
//        this.employeeId = employeeId;
//    }
//
//    @DynamoDbAttribute("firstName")
//    public String getFirstName() {
//        return firstName;
//    }
//
//    public void setFirstName(String firstName) {
//        this.firstName = firstName;
//    }
//    @DynamoDbAttribute("lastName")
//    public String getLastName() {
//        return lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }
//
//    @DynamoDbAttribute("email")
//    public String getEmail() {
//        return email;
//    }
//
//    public void setEmail(String email) {
//        this.email = email;
//    }
//
//    @DynamoDbAttribute("department")
//    public Department getDepartment() {
//        return department;
//    }
//
//    public void setDepartment(Department department) {
//        this.department = department;
//    }
}
